// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASqgjNur4v_rI4P6XYKgRSMlwnK-V-hU8',
    appId: '1:2591655678:web:4da6e78df1282638cc47af',
    messagingSenderId: '2591655678',
    projectId: 'todofirebase-353cc',
    authDomain: 'todofirebase-353cc.firebaseapp.com',
    storageBucket: 'todofirebase-353cc.appspot.com',
    measurementId: 'G-08FF6BKDTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0JODVEa0jFJfK-vkQjdRuimcnvJZiu6o',
    appId: '1:2591655678:android:42d0c4ed51fd64d4cc47af',
    messagingSenderId: '2591655678',
    projectId: 'todofirebase-353cc',
    storageBucket: 'todofirebase-353cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDExZYQoStYUN2upJS_kgurbrZdx4Pz9k',
    appId: '1:2591655678:ios:5a3cf1e8e285b1d7cc47af',
    messagingSenderId: '2591655678',
    projectId: 'todofirebase-353cc',
    storageBucket: 'todofirebase-353cc.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );
}
